### ISSUE TITLE
How to install??

### ISSUE THREAD

**Issue by habakuk40** [haocong/odroid-gpiou3p#1]
Hello!

I am actually trying to write sergey sgologuzov- but it is not possible to contact him for "odroid-c2-gpio" questions:
I am new to nodered.

I clone git your repository to my /.node-red/node_modules - directory successfully!

Do youknow how to install it that I can use it in node red with

var gpio = require('odroid-c2-gpio');

??

**Comment by haocong** [comment]
`npm install odroid-gpiou3p`

**Comment by habakuk40** [comment]
@hoacong:
when I do:

npm install odroid-c2-gpio

I get:
    odroid@odroid:~/.node-red/node_modules$ npm install odroid-c2-gpio
   + odroid-c2-gpio@0.0.2
   added 2 packages from 1 contributor, removed 1 package, updated 1 package and audited 4807 
   packages in 21.636s
   found 32 vulnerabilities (2 low, 10 moderate, 20 high)
   run `npm audit fix` to fix them, or `npm audit` for details

                 \u2502                 npm update check failed                  \u2502
                 \u2502           Try running with sudo or get access            \u2502
                 \u2502           to the local update config store via           \u2502
                 \u2502 sudo chown -R $USER:$(id -gn $USER) /home/odroid/.config \u2502


and the package "odroid-c2-gpio" keeps on failing in the browsers node.

what amI doing wrong hoacong?

**Comment by haocong** [comment]
> @hoacong:
> when I do:
> 
> npm install odroid-c2-gpio
> 
> I get:
> odroid@odroid:~/.node-red/node_modules$ npm install odroid-c2-gpio
> 
> * odroid-c2-gpio@0.0.2
>   added 2 packages from 1 contributor, removed 1 package, updated 1 package and audited 4807
>   packages in 21.636s
>   found 32 vulnerabilities (2 low, 10 moderate, 20 high)
>   run `npm audit fix` to fix them, or `npm audit` for details
>   ```
>           \u2502                 npm update check failed                  \u2502
>           \u2502           Try running with sudo or get access            \u2502
>           \u2502           to the local update config store via           \u2502
>           \u2502 sudo chown -R $USER:$(id -gn $USER) /home/odroid/.config \u2502
>   ```
> 
> and the package "odroid-c2-gpio" keeps on failing in the browsers node.
> 
> what amI doing wrong hoacong?

https://www.npmjs.com/search?q=odroid-c2-gpio

can't find this package in npm registry

**Comment by habakuk40** [comment]
check this plz:

https://github.com/Joebots/odroid-c2-gpio

**Comment by haocong** [comment]
> check this plz:
> 
> https://github.com/Joebots/odroid-c2-gpio

try this
`npm install Joebots/odroid-c2-gpio`
